# ビルドステージ
FROM golang:1.24.2-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -v -trimpath -buildvcs=false -o /batch ./cmd/batch

# 実行ステージ
FROM gcr.io/distroless/static-debian12

COPY --from=builder /batch /batch

ENTRYPOINT ["/batch"]
