// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/v1/book.proto

package book_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RandomBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomBooksRequest) Reset() {
	*x = RandomBooksRequest{}
	mi := &file_api_v1_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomBooksRequest) ProtoMessage() {}

func (x *RandomBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomBooksRequest.ProtoReflect.Descriptor instead.
func (*RandomBooksRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_book_proto_rawDescGZIP(), []int{0}
}

func (x *RandomBooksRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Isbn          string                 `protobuf:"bytes,2,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      string                 `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Authors       string                 `protobuf:"bytes,5,opt,name=authors,proto3" json:"authors,omitempty"`
	Publisher     string                 `protobuf:"bytes,6,opt,name=publisher,proto3" json:"publisher,omitempty"`
	PublishedDate string                 `protobuf:"bytes,7,opt,name=published_date,json=publishedDate,proto3" json:"published_date,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	BookUrl       string                 `protobuf:"bytes,9,opt,name=book_url,json=bookUrl,proto3" json:"book_url,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_api_v1_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_api_v1_book_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Book) GetAuthors() string {
	if x != nil {
		return x.Authors
	}
	return ""
}

func (x *Book) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *Book) GetPublishedDate() string {
	if x != nil {
		return x.PublishedDate
	}
	return ""
}

func (x *Book) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Book) GetBookUrl() string {
	if x != nil {
		return x.BookUrl
	}
	return ""
}

func (x *Book) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type RandomBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomBooksResponse) Reset() {
	*x = RandomBooksResponse{}
	mi := &file_api_v1_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomBooksResponse) ProtoMessage() {}

func (x *RandomBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomBooksResponse.ProtoReflect.Descriptor instead.
func (*RandomBooksResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_book_proto_rawDescGZIP(), []int{2}
}

func (x *RandomBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_api_v1_book_proto protoreflect.FileDescriptor

const file_api_v1_book_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/book.proto\x12\abook.v1\"*\n" +
	"\x12RandomBooksRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x95\x02\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04isbn\x18\x02 \x01(\tR\x04isbn\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x04 \x01(\tR\bsubtitle\x12\x18\n" +
	"\aauthors\x18\x05 \x01(\tR\aauthors\x12\x1c\n" +
	"\tpublisher\x18\x06 \x01(\tR\tpublisher\x12%\n" +
	"\x0epublished_date\x18\a \x01(\tR\rpublishedDate\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x19\n" +
	"\bbook_url\x18\t \x01(\tR\abookUrl\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\":\n" +
	"\x13RandomBooksResponse\x12#\n" +
	"\x05books\x18\x01 \x03(\v2\r.book.v1.BookR\x05books2Z\n" +
	"\vBookService\x12K\n" +
	"\x0eGetRandomBooks\x12\x1b.book.v1.RandomBooksRequest\x1a\x1c.book.v1.RandomBooksResponseB7Z5github.com/taiki-umetsu/ndc007-bookpicker/api/book_v1b\x06proto3"

var (
	file_api_v1_book_proto_rawDescOnce sync.Once
	file_api_v1_book_proto_rawDescData []byte
)

func file_api_v1_book_proto_rawDescGZIP() []byte {
	file_api_v1_book_proto_rawDescOnce.Do(func() {
		file_api_v1_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_book_proto_rawDesc), len(file_api_v1_book_proto_rawDesc)))
	})
	return file_api_v1_book_proto_rawDescData
}

var file_api_v1_book_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_book_proto_goTypes = []any{
	(*RandomBooksRequest)(nil),  // 0: book.v1.RandomBooksRequest
	(*Book)(nil),                // 1: book.v1.Book
	(*RandomBooksResponse)(nil), // 2: book.v1.RandomBooksResponse
}
var file_api_v1_book_proto_depIdxs = []int32{
	1, // 0: book.v1.RandomBooksResponse.books:type_name -> book.v1.Book
	0, // 1: book.v1.BookService.GetRandomBooks:input_type -> book.v1.RandomBooksRequest
	2, // 2: book.v1.BookService.GetRandomBooks:output_type -> book.v1.RandomBooksResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_book_proto_init() }
func file_api_v1_book_proto_init() {
	if File_api_v1_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_book_proto_rawDesc), len(file_api_v1_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_book_proto_goTypes,
		DependencyIndexes: file_api_v1_book_proto_depIdxs,
		MessageInfos:      file_api_v1_book_proto_msgTypes,
	}.Build()
	File_api_v1_book_proto = out.File
	file_api_v1_book_proto_goTypes = nil
	file_api_v1_book_proto_depIdxs = nil
}
