openapi: 3.0.0
info:
  title: NDC007 BookPicker API
  version: "1.0.0"
  description: API for retrieving random book entries from the BookPicker database
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/v1/books/random:
    get:
      summary: Retrieve random books
      operationId: getRandomBooks
      parameters:
        - name: count
          in: query
          description: Number of books to return (1-10)
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 10
            default: 3
      responses:
        '200':
          description: A JSON array of Book objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: schemas/Book.yaml
        '400':
          description: Invalid request parameter
          content:
            application/json:
              schema:
                $ref: schemas/Error.yaml
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: schemas/Error.yaml