openapi: 3.0.0
info:
  title: NDC007 BookPicker API
  version: "1.0.0"
  description: API for retrieving random book entries from the BookPicker database
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/v1/books/random:
    get:
      summary: Retrieve random books
      operationId: getRandomBooks
      parameters:
        - name: count
          in: query
          description: Number of books to return (1-10)
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 10
            default: 3
      responses:
        '200':
          description: A JSON array of Book objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '400':
          description: Invalid request parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        isbn:
          type: string
        title:
          type: string
        subtitle:
          type: string
        authors:
          type: string
        publisher:
          type: string
        publishedDate:
          type: string
          description: |
            Publication date. Supports:
            - Full date: YYYY-MM-DD
            - Year-month only: YYYY-MM
            - Year only: YYYY
          pattern: '^\d{4}(?:-\d{2}(?:-\d{2})?)?$'
        description:
          type: string
        bookUrl:
          type: string
          format: uri
        imageUrl:
          type: string
          format: uri
      required:
        - id
        - isbn
        - title
        - authors
        - publisher
        - publishedDate
        - description
        - bookUrl
        - imageUrl
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
          required:
            - code
            - message
      required:
        - error
