name: Deploy API via Cloud Build

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ vars.WIF_PROVIDER }}"
          service_account: "${{ vars.WIF_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Submit Cloud Build (API)
        id: cloudbuild
        run: |
          BUILD_ID=$(gcloud builds submit --config=cloudbuild-api.yaml \
            --substitutions="\
              _SERVICE_NAME=${{ vars.API_SERVICE_NAME }},\
              _REGION=${{ vars.REGION }},\
              _IMAGE_NAME=${{ vars.API_IMAGE_NAME }},\
              _SERVICE_ACCOUNT=${{ vars.SERVICE_ACCOUNT }},\
              _CLOUDSQL_INSTANCE=${{ vars.CLOUDSQL_INSTANCE }}" \
            --no-source \
            --no-stream \
            --format='value(metadata.build.id)')
          
          echo "BUILD_ID=$BUILD_ID" >> "$GITHUB_ENV"

      - name: Wait for build result
        run: |
          echo "Waiting for build $BUILD_ID..."
          STATUS=$(gcloud builds describe "$BUILD_ID" --format='value(status)')
          
          echo "Build status: $STATUS"
          if [[ "$STATUS" != "SUCCESS" ]]; then
            echo "Build failed"
            exit 1
          fi
