name: Deploy Batch via Cloud Build

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ vars.WIF_PROVIDER }}"
          service_account: "${{ vars.WIF_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Submit Cloud Build (Batch)
        run: |
          gcloud builds submit \
            --config=cloudbuild-batch.yaml \
            --quiet \
            --substitutions="\
          _PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},\
          _REGION=${{ vars.REGION }},\
          _IMAGE_NAME=${{ vars.BATCH_IMAGE_NAME }},\
          _JOB_NAME=${{ vars.BATCH_JOB_NAME }},\
          _SCHEDULER_NAME=${{ vars.SCHEDULER_NAME }},\
          _SERVICE_ACCOUNT=${{ vars.SERVICE_ACCOUNT }},\
          _DB_SECRET=${{ vars.DB_SECRET }},\
          _GO_ENV_SECRET=${{ vars.GO_ENV_SECRET }},\
          _CINII_SECRET=${{ vars.CINII_SECRET }},\
          _BOOKS_KEY_SECRET=${{ vars.BOOKS_KEY_SECRET }},\
          _CLOUDSQL_INSTANCE=${{ vars.CLOUDSQL_INSTANCE }},\
          _SCHEDULE_TIME=${{ vars.SCHEDULE_TIME }}\
          "