name: Deploy API via Cloud Build

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate via Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ vars.WIF_PROVIDER }}"
          service_account: "${{ vars.WIF_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}

      - name: Submit Cloud Build (API)
        run: |
          BUILD_ID=$(gcloud builds submit \
          --config=cloudbuild-api.yaml \
          --async \
          --format="value(name)" \
          --substitutions="\
          _SERVICE_NAME=${{ vars.API_SERVICE_NAME }},\
          _REGION=${{ vars.REGION }},\
          _IMAGE_NAME=${{ vars.API_IMAGE_NAME }},\
          _SERVICE_ACCOUNT=${{ vars.SERVICE_ACCOUNT }},\
          _CLOUDSQL_INSTANCE=${{ vars.CLOUDSQL_INSTANCE }}\
          ")

          echo "Waiting for build to complete..."
          while true; do
            STATUS=$(gcloud builds describe $BUILD_ID --format="value(status)" 2>/dev/null || echo "UNKNOWN")
            echo "Current status: $STATUS"
            
            if [ "$STATUS" = "SUCCESS" ]; then
              echo "Build completed successfully!"
              break
            elif [ "$STATUS" = "FAILURE" ] || [ "$STATUS" = "CANCELLED" ] || [ "$STATUS" = "TIMEOUT" ]; then
              echo "Build failed with status: $STATUS"
              echo "Check logs at: https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=${{ vars.PROJECT_ID }}"
              exit 1
            fi
            
            sleep 30
          done
